### ISSUE TITLE
Faster Audio Preload failing to work quickly (possibly at all)

### ISSUE THREAD

**Issue by AndyTheBrave** [kandashi/faster-audio-preload#1]
**Foundry Version:** 9.242

**Module Version:** 0.1.01

**System: Pathfinder 1e:** 0.80.4 (not using the latest build since it had a serious bug for me that prevented me from adding Spells to character sheets)

Previously when I used the module, I would select Auto Preload, and I would wait about nine seconds after doing so and my players would hear the brief sound clip or full song immediately on my clicking the 'Play' button. I have six players in my game. Presently, whether it's a 2 second clip or a full 2:30-3:30 minute long song, it fails for almost all of them. One player with Fiber Internet was able to hear it usually. Even if I pause the song and wait 10-20 seconds almost all of them don't hear it.

I tried to see if maybe this was an issue with having too many sound files auto-preloaded, so I went through and sure enough I had about 14 audio files preloaded. So I unchecked them from their boxes and tried again that same session. No good--it didn't change it at all. Though to be honest I'm not even sure how much that effects the performance of the module.

That's about all I can think of to share for the issue.

**Comment by kandashi** [comment]
That isnt what that button does. If selected, that will preload the **entire** playlist upon a user joining.

**Comment by kandashi** [comment]
From what I can tell, the module is functioning as intended
